miscellaneous fixes
extended tcp support for Heos a.o. (now can receive connections),
extended Classe support, minor fix i2c interface, minor change
configure script, updated the manual

diff --git a/src/configure b/src/configure
--- a/src/configure
+++ b/src/configure
@@ -200,6 +200,8 @@ process_arguments()
 
 echo Configuring Synchronator
 
+type "pkg-config" >/dev/null 2>&1 || { echo >&2 "Can not find pkg-config. Aborting."; exit 1; }
+
 echo "// automatically generated file" > config.h
 
 process_arguments $@
